<a href="https://colab.research.google.com/github/ajaykumar080286/feature_engineering/blob/main/1_Working_With_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

**Opening CSV file using CSV**

In [8]:
df=pd.read_csv("placement (2).csv")

In [9]:
df.head(5)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

**3. Opening a csv file from an URL**

In [10]:
import pandas as pd

# Example: CSV file hosted online
url = "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"

# Read CSV from URL
df = pd.read_csv(url)

df.head()

   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30

In [11]:
import requests
from io import StringIO

url = "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]

In [12]:
# URL of the CSV file
url = "https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"

# Fetch the file using requests
response = requests.get(url)

# Check if request was successful
if response.status_code == 200:
    # Convert the response text into a file-like object
    csv_data = StringIO(response.text)

    # Read into pandas DataFrame
    df = pd.read_csv(csv_data)

    print(df.head())
else:
    print("Failed to fetch CSV file. Status code:", response.status_code)

   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30

**4. Sep Parameter**

In [28]:
df=pd.read_csv("movie_titles_metadata.tsv", sep="\t", names=["SNo", "Name","Year","Tax","Amount","Iteam"])

In [29]:
df.head()

,SNo,Name,Year,Tax,Amount,Iteam
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']

**5. Index_col parameter**

In [31]:
df=pd.read_csv("aug_train.csv", index_col="enrollee_id")
df.head()

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0