<a href="https://colab.research.google.com/github/ajaykumar080286/feature_engineering/blob/main/26_missing_indicator_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [41]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/feature_engineering/main/train.csv",usecols=['Age','Fare','Survived'])

In [42]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [43]:
X=df.iloc[:,1:3]
y=df.iloc[:,0:1]

In [44]:
simple_inpute=SimpleImputer()

In [45]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2, random_state=42)

In [21]:
X_train_trf=simple_inpute.fit_transform(X_train)
X_test_trf=simple_inpute.transform(X_test)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [30]:
lr=LogisticRegression()
lr.fit(X_train_trf,y_train)
accuracy_score(lr.predict(X_test_trf),y_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.6480446927374302

In [31]:
missing=MissingIndicator()

In [34]:
X_train_missing=missing.fit_transform(X_train)
X_test_missing=missing.transform(X_test)

In [36]:
X_train["Age_impute"]=X_train_missing
X_test["Age_impute"]=X_test_missing

In [38]:
X_train.head(2)

      Age  Fare  Age_impute
331  45.5  28.5       False
733  23.0  13.0       False

In [39]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

accuracy_score(y_test,y_pred)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.6368715083798883

In [46]:
#This is good flolow
si = SimpleImputer(add_indicator=True)

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

accuracy_score(y_test,y_pred)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.6368715083798883